const express = require('express');
const router = express.Router();
const ctrlUser = require('../controllers/user.controller');
const jwtHelper = require('../config/jwtHelper');

router.post('/edit/:email/:domaine/:name',ctrlUser.saveinfo);
router.post('/reserve/:time',ctrlUser.reserve);
router.post('/rate/:C_email/:E_email/:rate',ctrlUser.rate);
router.post('/register', ctrlUser.register);
router.post('/authenticate', ctrlUser.authenticate);
router.post('/delete/:email/:day', ctrlUser.delete);
router.put('/ModName/:email/:newName', ctrlUser.ModName);
router.put('/ModLastName/:email/:newLastName', ctrlUser.ModLastName);
router.put('/ModEmail/:email/:newEmail', ctrlUser.ModEmail);
router.put('/ModPass/:email/:newPass', ctrlUser.ModPass);
router.put('/ModDomaine/:email/:newDomaine', ctrlUser.ModDomaine);
router.post('/putProcess/:email/:day/:time',ctrlUser.putProcess);
router.post('/deleteProcess/:email/:day/:time', ctrlUser.deleteProcess);
router.get('/getProcess/:email/:day', ctrlUser.getProcess) ;
router.post('/update/:id', ctrlUser.update);
router.get('/userProfile',jwtHelper.verifyJwtToken, ctrlUser.userProfile);
router.get('/consult/:email', ctrlUser.getconsult);
router.get('/searchName/:Search_Name', ctrlUser.searchbyName) ;
router.get('/expert/:email', ctrlUser.getall) ;
router.get('/searchDomaine/:Search_Domaine', ctrlUser.searchbyDomaine) ;
//router.get('/searchName/:Search_Name/:dispoday', ctrlUser.searchbyName) ;
//router.get('/searchDomaine/:Search_Domaine/:dispoday', ctrlUser.searchbyDomaine) ;
router.get('/daydetails/:email', ctrlUser.getdays) ;
router.get('/casecolor/:expertName/:consultday', ctrlUser.getcolor) ;
router.get('/reservation/:email', ctrlUser.getreservation) ;
router.get('/expertDetails/:_id', ctrlUser.getexpert) ;
router.get('/getrate/:email', ctrlUser.getrate) ;
router.get('/getNotif/:email', ctrlUser.getNotif);
module.exports = router;
